Grouping
PimPaardekooper/zombie_apocalypse pull request #56
Opened 2020-01-27 12:15 UTC by PimPaardekooper2

grouping can be turned off.

2020-01-27 15:50 UTC, Zeepaardje98 commented
Zet de png even in een gitignore

2020-01-28 13:59 UTC, jtbuter requested changes

2020-01-28 13:59 UTC, jtbuter commented on apocalypse_sim/data.txt
> +"hello"
What is this?

2020-01-28 13:59 UTC, jtbuter commented on apocalypse_sim/grid_map/map_layouts.py
> +        elif os.environ["mode"] == "5":
This mode can be removed as it was only used for reference when creating the poster

2020-01-28 13:59 UTC, jtbuter commented on apocalypse_sim/grid_map/map_layouts.py
> +    def seperation_map(self):
This method can be removed.

2020-01-28 13:59 UTC, jtbuter commented on apocalypse_sim/grid_map/map_layouts.py
> +    def alignment_map(self):
This method can be removed.

2020-01-28 13:59 UTC, jtbuter commented on apocalypse_sim/grid_map/map_layouts.py
> +    def cohesion_map(self):
This method can be removed.

2020-01-28 13:59 UTC, jtbuter commented on apocalypse_sim/grid_map/map_layouts.py
> +    def avoid_zombie_search_brain(self):
This method can be removed

2020-01-28 13:59 UTC, jtbuter commented on apocalypse_sim/grid_map/map_layouts.py
> +    def __init__(self, agent_type, positions, color=""):
Add description for color parameter

2020-01-28 13:59 UTC, jtbuter commented on apocalypse_sim/model.py
>          Initializes the apocalypse object, makes the grid and put agents on
Add grouping parameter description

2020-01-28 13:59 UTC, jtbuter commented on apocalypse_sim/model_representation/mode.py
> +    elif os.environ["mode"] == "5":
I think this mode is no longer needed

2020-01-28 13:59 UTC, jtbuter commented on apocalypse_sim/model_representation/portrayals.py
> +
This can be removed

2020-01-28 13:59 UTC, jtbuter commented on apocalypse_sim/simulation-pim.py
> +from model import Apocalypse
I think this file can be removed in it's entirety, since it doesn't do multithreaded experiments.

2020-01-28 16:17 UTC, jtbuter approved these changes

2020-01-28 16:23 UTC, merged